#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x


STORAGE="$2"
STORAGE_TARGET="$3"

print_help(){
  cat<<EOF
  
Usage: dokku storage[:copy]

    Copy/clone existing storage folder.

Additional commands:  
    storage:copy <storage source path> <storage target path>, Copy a existing storage
    storage:remove <storage source path>, Delete a folder
    
EOF
  return
}

check_storage() {
  if [[ ! -d "$STORAGE" ]]; then
    echo "You must specify a existing storage (absolute path)"
    exit 1
  fi
}

check_storage_target() {
  if [[ -z "$STORAGE_TARGET" ]]; then
    echo "You must specify a existing storage target (absolute path)"
    exit 1
  fi
}

storage_target_exists() {
  if [[ -d "$STORAGE_TARGET" ]]; then
    echo "Storage target $STORAGE_TARGET already exists."
    exit 1
  fi
}

case "$1" in
  storage:copy)
  	check_storage
  	check_storage_target
  	storage_target_exists

    echo "Copy storage from $STORAGE to $STORAGE_TARGET"
	cp -Rp $STORAGE $STORAGE_TARGET
    ;;

  storage:remove)
  	check_storage

    echo "Remove storage folder $STORAGE ..."
	# Add "%dokku ALL=(ALL) NOPASSWD:/bin/rm -rf /var/lib/dokku/data/storage/*" to a new sudoers file in /etc/sudoers.d/
	sudo /bin/rm -rf $STORAGE
    ;;

  help | storage:help)
    if [[ -n $DOKKU_API_VERSION ]]; then
      print_help
    else
      cat && print_help
    fi
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac